### ISSUE TITLE
Don't repatch every 60 seconds 

### ISSUE THREAD

**Issue by sandreae** [noiseorchestra/jacktrip_pypatcher#84]
The patcher seems to be re-running every 60 seconds. Think it might be something to do with `watchgod`. More investigation needed.

**Comment by madwort** [comment]
due to this change, which I don't remember making!
https://github.com/noiseorchestra/jacktrip_pypatcher/commit/700e8de2c761787dce6a6bc8e87cd68eecd28557
Need to verify that the touch repatch is working and then increase this back to some large number (or find a better way to do this...)

**Comment by madwort** [comment]
well, the touch is working:

```
# connect client at 12:08
root@localhost:/home/sam/jacktrip_pypatcher# ls -lh /var/tmp/jacktrip_pypatcher
-rw-r--r-- 1 sam sam 0 Nov 21 12:08 /var/tmp/jacktrip_pypatcher
# disconnect client
# connect client at 12:11
root@localhost:/home/sam/jacktrip_pypatcher# ls -lh /var/tmp/jacktrip_pypatcher
-rw-r--r-- 1 sam sam 0 Nov 21 12:11 /var/tmp/jacktrip_pypatcher
```

**Comment by madwort** [comment]
looking at the listener then!

**Comment by madwort** [comment]
huh, well, it's working fine now

```
ov 21 12:13:45 localhost jacktrip[861]: ---------------------------------------------------------
Nov 21 12:13:45 localhost jacktrip[861]: UDP Socket Receiving in Port: 61000
Nov 21 12:13:45 localhost jacktrip[861]: ---------------------------------------------------------
Nov 21 12:13:45 localhost jacktrip[861]: Waiting for Peer...
Nov 21 12:13:45 localhost jacktrip[861]: JackTrip HUB SERVER: Total Running Threads:  1
Nov 21 12:13:45 localhost jacktrip[861]: ===============================================================
Nov 21 12:13:45 localhost jacktrip[861]: Received Connection from Peer!
Nov 21 12:13:45 localhost jacktrip[861]: spawning jacktripWorker
Nov 21 12:13:45 localhost python3[863]: client 'lsp' registered
Nov 21 12:13:45 localhost python3[863]: lsp  starts with '..'? (therefore JT client?) False
Nov 21 12:13:45 localhost python3[863]: client 'lsp' unregistered
Nov 21 12:13:45 localhost python3[863]: lsp  starts with '..'? (therefore JT client?) False
Nov 21 12:13:45 localhost jacktrip[861]: JackTrip HUB SERVER: Waiting for client connections...
Nov 21 12:13:45 localhost jacktrip[861]: JackTrip HUB SERVER: Hub auto audio patch disabled
Nov 21 12:13:45 localhost jacktrip[861]: =======================================================
Nov 21 12:13:45 localhost python3[862]: Process Process-7:
Nov 21 12:13:45 localhost python3[862]: Traceback (most recent call last):
Nov 21 12:13:45 localhost python3[862]:   File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
Nov 21 12:13:45 localhost python3[862]:     self.run()
Nov 21 12:13:45 localhost python3[862]:   File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
Nov 21 12:13:45 localhost python3[862]:     self._target(*self._args, **self._kwargs)
Nov 21 12:13:45 localhost python3[862]:   File "/home/sam/jacktrip_pypatcher/patcher_watchgod.py", line 11, in foobar
Nov 21 12:13:45 localhost python3[862]:     time.sleep(60)
Nov 21 12:13:45 localhost python3[862]: KeyboardInterrupt
Nov 21 12:13:45 localhost python3[863]: client 'MadwortAutoPatcher' registered
Nov 21 12:13:45 localhost python3[863]: MadwortAutoPatcher  starts with '..'? (therefore JT client?) False
Nov 21 12:13:45 localhost python3[862]: === JackTrip clients ===
Nov 21 12:13:45 localhost python3[862]: client count: 1
Nov 21 12:13:45 localhost python3[862]: clients: ['..ffff.79.73.8.80']
Nov 21 12:13:45 localhost python3[862]: === LADSPA ports ===
```

**Comment by madwort** [comment]
the `KeyboardInterrupt` is the listener observing the file being touched, interrupting the 60sec sleep & causing the loop to go around & do a repatch.
Hmmm. 
It definitely wasn't working when we were in the middle of the Sloth Racket session - because I increased the timeout to 180sec & Seth wasn't getting quickly reconnected after a dropout, he had to wait for it to timeout.
Hmmmm.
